:filename: dukecon/src/main/asciidoc/de/01_introduction_and_goals.adoc
[[section-introduction-and-goals]]
==	Einführung und Ziele

Dukecon ist eine Anwendung zur Visualisierung von Konferenzenprogrammen. Die Idee ist auf der Javaland 2015 entstanden.

=== Aufgabenstellung

Beim Besuch einer Konferenz möchte man sich vor Ort über die nächsten Vorträge informieren. Oftmals ist der Zugriff auf das Internet und damit auf die Webseite der Konferenz stark eingeschränkt. Das Ziel von Dukecon ist das Bereitstellen des Konferenzprogramms auf mobilen Geräten, wobei man nach einem initialen Holen der Daten auch offline arbeiten können muß.

Da viele Besucher im Vorfeld einer Konferenz das Programm auf anderen Geräten (Desktoprechner, Laptop, Tablet) anschauen und ggf. Favoriten auswählen, soll die Sychronisation über die verschiedenen Geräte erfolgen können, so dass vor Ort auf dem mobilen Endgerät die ausgewählten Vorträge wieder angezeigt werden können.

=== Qualitätsziele

* Offlinefähigkeit
* Bedienbarkeit
* Datensicherheit
* Synchronisation über verschiedene Clients
* Anwendbar auf verschiedene Konferenzen

=== Stakeholder

Die folgende Tabelle zeigt Ihre konkreten Stakeholder für das System sowie deren Interessen oder Beteiligung.

[cols="1,2" options="header"]
.Stakeholder des Systems
|===
|Rolle |Beschreibung
|Auftraggeber | DOAG/iJUG für die Javaland-Konferenz
|Fachbereich | DOAG und Kern-Team
|Entwickler | JUG Darmstadt, JUG Kaiserslautern und Einzelpersonen
|Betrieb | Wartung der Stage- und Produktionsumgebungen
|Tester | Treffen beim Usability-Testessen
|Kern-Team | Entwickler, Architekten, Betriebler
|Anwender | Konferenzbesucher
|===
