[[section-system-scope-and-context]]

== Kontextabgrenzung


["plantuml", "dukecon-systemcontext", "svg"]
------------------------------------------------
include::../images/systemcontext.puml[]
------------------------------------------------

=== Schnittstellen
Die DukeCon Anwendung kommuniziert mit seiner Umgebung über folgende Schnittstellen:

.DOAG Backoffice (externes System):
Als Datenlieferant nutzt DukeCon eine BackOffice-Lösung der DOAG (Deutsche ORACLE-Anwendergruppe e.V.). Ein Back-Officer der DOAG aktualisiert das Konferenzprogramm, aktualisierte Daten stehen damit auch der DukeCon-Anwendung zur Verfügung.

.Konferenzteilnehmer (Anwender):
Die DukeCon-Anwendung offeriert eine Benutzungsschnittstelle für Konferenzteilnehmer. Sie ermöglicht das Zusammenstellen und Abrufen des Konferenzplanes. 
 
=== Technologien:
.DOAG-Backoffice Lösung und DukeCon-Anwendung:
Übertragung der Konferenzdaten aus der DOAG-Backoffice Lösung in die DukeCon-Anwendung mittels eines REST-Services.
(Beispiel-Datensatz)

.DukeCon-Anwendung und Konferenzteilnehmer:
Nutzungsschnittstelle implementiert in HTML5 mit JavaScript auf Basis von Knockout. Parallel dazu ist eine natives Frontend auf Basis von Flex implementiert.