@startuml
skinparam handwritten true

actor :DukeCon Officer:
actor :Conference Participant:

node "Web-Browser Device" {
    [DukeCon Admin] <<Client>>
    [DukeCon PWA] <<Client>> as DukeConPwa
}

node "Native Android Device" {
    [DukeCon Android] <<Client>> as DukeConAndroid
}

cloud "DukeCon Infrastructure" {
    node DukeCon-Server <<Docker : Java8>> {
        [DukeCon] <<Service>>
    }

    node KeyCloak-Server <<Docker : WildFly>> {
        [KeyCloak] <<Service>>
    }

    node DukeCon-DB <<Docker : PostgreSQL>> {
        database DukeCon_PostgreSQL
    }

    node KeyCloak-DB <<Docker : PostgreSQL>> {
        database KeyCloak_PostgreSQL
    }
    [DukeCon] --> [DukeCon_PostgreSQL] : JDBC
    [KeyCloak] --> [KeyCloak_PostgreSQL] : JDBC
}

:DukeCon Officer: -down-> (DukeCon Admin) : "Update noof participants /\nEnforce data update"

:Conference Participant: -down-> DukeConAndroid : Compile conference program
:Conference Participant: -down-> DukeConPwa : Compile conference program

(DukeConPwa) -down-> (DukeCon) : Conf. Data/Favorites
(DukeConPwa) -down-> (KeyCloak) : Authenticate

(DukeConAndroid) -down-> (DukeCon) : Conf. Data/Favorites
(DukeConAndroid) -down-> (KeyCloak) : Authenticate

@enduml