@startuml
skinparam handwritten true

actor :DukeCon Officer:
actor :Conference Participant:
actor :Speaker:

node "Web-Browser Device" {
    [DukeCon Admin] <<Client>>
    [DukeCon PWA] <<Client>> as DukeConPwa
}

node "Native Android Device" {
    [DukeCon Android] <<Client>> as DukeConAndroid
}

cloud "DOAG Infrastructure" {
    [DOAG Formes] <<Service>> as DoagFormes #lightgreen
}

cloud "DukeCon Infrastructure" {
    node DukeCon-Server <<Docker : Java8>> {
        [DukeCon] <<Service>> as DukeconService
    }

    node DukeCon-DB <<Docker : PostgreSQL>> {
        database DukeCon_PostgreSQL
    }
    [DukeconService] --> [DukeCon_PostgreSQL] : JDBC

    node DukeCon-Feedback-Server <<Docker : Java9>> #red {
        [DukeCon-Feedback] <<Service>> as DukeconFeedbackService #red
    }

    node DukeCon-Feedback-DB <<Docker : PostgreSQL>> #red {
        database DukeCon_Feedback_PostgreSQL as DukeconFeedbackDB #red
    }
    [DukeconFeedbackService] ..> DukeconFeedbackDB : JDBC
    DukeconService <.right. DukeconFeedbackService : Retrieve Talk + Speaker Data

    node DukeCon-Mail-Server <<Docker>> #red {
        [SMTP Server] <<Postfix>> as DukeconPostfix #red
    }
    [DukeconFeedbackService] ..> DukeconPostfix : SMTP

    node KeyCloak-Server <<Docker : WildFly>> {
        [KeyCloak] <<Service>>
    }

    node KeyCloak-DB <<Docker : PostgreSQL>> {
        database KeyCloak_PostgreSQL
    }
    [KeyCloak] --> [KeyCloak_PostgreSQL] : JDBC
}

DoagFormes -right-> DukeconService : Update Talk + Speaker Data

:DukeCon Officer: -down-> (DukeCon Admin) : "Update noof participants /\nEnforce data update"

:Conference Participant: -down-> DukeConAndroid : Compile conference program
:Conference Participant: -down-> DukeConPwa : Compile conference program

(DukeConPwa) -down-> (DukeconService) : Conf. Data/Favorites
(DukeConPwa) .down-> (DukeconFeedbackService) : Feedback for talks
(DukeConPwa) -down-> (KeyCloak) : Authenticate

(DukeConAndroid) -down-> (DukeconService) : Conf. Data/Favorites
(DukeConAndroid) .down-> (DukeconFeedbackService) : Feedback for talks
(DukeConAndroid) -down-> (KeyCloak) : Authenticate

DukeconPostfix --> :Speaker: : Mail

@enduml