@startuml
skinparam linetype ortho

actor browser as "User/Browser"
participant html5 as "HTML5-Client"
participant Keycloak
participant server as "Rest-Server"

browser -> html5 : Request (not authenticated)
browser <-- html5 : Redirect to Keycloak
browser -> Keycloak : Request (not authenticated)
browser <-- Keycloak : Login page
browser -> Keycloak : Choose social login
browser <-- Keycloak : Redirect to social login page
browser -> Keycloak : Social authenticate
browser -> Keycloak : Login
browser <-- Keycloak : Redirect to client (with access and id token)
html5 -> server : JavaScript call to REST\nbackend (with Bearer-Token)
html5 <-- server
browser <-- html5 : Response
@enduml
